// Generated by CoffeeScript 1.4.0
(function() {
  var namespace,
    __slice = [].slice;

  namespace = function(target, name, block) {
    var item, top, _i, _len, _ref, _ref1;
    if (arguments.length < 3) {
      _ref = [(typeof exports !== 'undefined' ? exports : window)].concat(__slice.call(arguments)), target = _ref[0], name = _ref[1], block = _ref[2];
    }
    top = target;
    _ref1 = name.split('.');
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      item = _ref1[_i];
      target = target[item] || (target[item] = {});
    }
    return block(target, top);
  };

  namespace('Hello.World', function(exports) {
    return exports.hi = function() {
      return console.log('Hi World!');
    };
  });

  namespace('Say.Hello', function(exports, top) {
    return exports.fn = function() {
      return top.Hello.World.hi();
    };
  });

  Say.Hello.fn();

}).call(this);
